### PR TITLE
Improve typescript support

### PR DESCRIPTION
**Pull request by sylcastaing**
Improve typescript definition file. #31

### CODE REVIEW

**Review by hernansartorio — APPROVED** [review]
Hi, sorry for the delay! I don't use Typescript currently so I haven't tested it, but this looks good to me. Thank you!

**Comment by Aryaman73** [comment]
@sylcastaing I think your commit might have broken Typescript compilation? You replaced `Date | undefined` with `Date | null`, but  Date _can_ be undefined (Typescript's defaults to `Date | undefined`)

image

I think if you wanted to add null support, your DateChangeCallback should be `Date | null | undefined`

**Comment by sylcastaing** [comment]
@Aryaman73 I don't remember but I think `setDate` always return `Date | null`. No `undefined` can be send. 

In this case the your `useState` is wrong. It should be : 
```typescript
const [date, setDate] = useState<Date | null>(null)
```

I don't use this library now. You can see with @hernansartorio. 

If `setDate` can return `undefined`, `DateChangeCallBack` can be changed to `Date | null | undefined`

**Comment by Aryaman73** [comment]
I _think_ the issue is that there is still inconsistency between `DateChangeCallback` and date in `DatePickerProps.` The former expects `Date | null` whereas the latter is just `Date` (which defaults to `Date | undefined`). 

As you can see here, even though myDate is `date | null` the date prop in the DatePicker component expects `Date | undefined.`
image

The inconsistency is here:
image

I've found that `const [myDate, setDate] = useState<Date | null>(null)` works for the component's onDateChang prop, and `const [myDate, setDate] = useState<Date>()` works for the component's date prop, so it's impossible to fulfil both props using useState.

Switching Line 46 to `Date | null` seems to fix the problem, but I'll investigate this a bit more to see if what I'm saying is correct before making a PR.

**Pull request merged**
